services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
     - db:/var/lib/postgresql/data

  backend:
    build:
      context: ./ase-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: ./ase-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      
volumes:
  db: 