services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5555:5432"
    volumes:
     - db:/var/lib/postgresql/data
     - ./db_init:/docker-entrypoint-initdb.d
volumes:
  db: 
